Web/YovevElectric.Web/Areas/Administration/Controllers/ImgController.cs
// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YovevElectric.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using CloudinaryDotNet;
    using CloudinaryDotNet.Actions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using YovevElectric.Common;
    using YovevElectric.Services.Data;
    using YovevElectric.Web.ViewModels.Img;
    using YovevElectric.Web.ViewModels.Product;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class ImgController : Controller
    {
        private readonly Cloudinary cloudinary;
        private readonly IImgService imgService;
        private readonly IProductsService productsService;

        public ImgController(Cloudinary cloudinary, IImgService imgService, IProductsService productsService)
        {
            this.cloudinary = cloudinary;
            this.imgService = imgService;
            this.productsService = productsService;
        }

        public IActionResult ImgUpload(string id)
        {
            var output = new ImgUploadViewModel { ProductId = id };

            return this.View(output);
        }

        [HttpPost]
        public async Task<IActionResult> ImgUpload(ImgUploadInputModel input)
        {
            if (input.ProductId == null)
            {
                return this.View("Error");
            }

            var imgPath = string.Empty;
            for (int i = 1; i <= 4; i++)
            {
                var file = (IFormFile)input.GetType().GetProperty("ProductImg" + i).GetValue(input, null);
                imgPath += await this.imgService.UploadImgAsync(file) + ",";
            }

            await this.imgService.AddImgToCurrentProductAsync(imgPath, input.ProductId);
            return this.Redirect($"/Administration/Administration/EditProduct?id={input.ProductId}");
        }

        public async Task<IActionResult> DeleteProductImg(string id, string imgNumber)
        {
            await this.imgService.DeleteProductImgFromProductAsync(id, int.Parse(imgNumber));

            return this.Redirect($"/Administration/Administration/EditProduct?id={id}");
        }

        public async Task<IActionResult> DeleteCategoryImg(string id)
        {
            await this.imgService.DeleteCategoryImgByIdAsync(id);

            return this.Redirect($"/Administration/Administration/EditCategory?id={id}");
        }
    }
}

Web/YovevElectric.Web/Areas/Administration/Views/Shared/EditImg.cshtml
@model YovevElectric.Web.ViewModels.Product.EditProductModel;
@using YovevElectric.Common;
@{
    ViewData["Title"] = "EditImg";
}


    <form method="post" dasp-controller="Files" runat="server" enctype="multipart/form-data" asp-area="Administration" asp-controller="Img" asp-action="ImgUpload">
        <div id="pic1">
            <br>
            <input type="hidden" asp-for="@Model.ImgEditModel.ImgEditViewModel.ProductId" name="ProductId" />
            <img id="img" src="@Model.ImgEditModel.ImgEditViewModel.ImgPath" class="defaultImg" alt="your image" />
            <br>
            <input type='file' name="productImg" onchange="readURL(this)" id="productImg" />
            <br>
            <button onclick="upload()" id="btnSubmit" type="submit" value="Upload Imgs" class="btn btn-primary">Качи снимката</button>
            <a onclick="readURL(this);" href="/Administration/Img/DeleteImg?id=@Model.ImgEditModel.ImgEditViewModel.ProductId" id="btn" class="btn btn-outline-secondary">Изтрий снимката</a>
            <br>
        </div>
    </form>

Web/YovevElectric.Web/Areas/Administration/Views/Shared/_EditImgPartial.cshtml
@model YovevElectric.Web.ViewModels.Product.EditProductModel;
@using YovevElectric.Common;
@{
    ViewData["Title"] = "EditImg";
}

<div style="margin-bottom:60px;">
    <form method="post" dasp-controller="Files" runat="server" enctype="multipart/form-data" asp-area="Administration" asp-controller="Img" asp-action="ImgUpload">
        <div class="row">
            <div id="pic1" style="float:left">
                <br>
                <input type="hidden" asp-for="@Model.ImgEditModel.ImgEditViewModel.ProductId" name="ProductId" />
                <img id="img1" src="@Model.ImgEditModel.ImgEditViewModel.ImgPath1" class="defaultImg" alt="your image" />
                <br>
                <input type='file' name="productImg1" onchange="readURL(this)" id="productImg1" />
                <br>
                <a onclick="readURL(this);" asp-area="Administration" asp-controller="Img" asp-action="DeleteProductImg" asp-route-id="@Model.ImgEditModel.ImgEditViewModel.ProductId" asp-route-imgNumber="1" id="btn1" class="btn btn-outline-secondary">Изтрий снимката</a>
                <br>
            </div>
            <div id="pic2" style="float:left">
                <br>
                <img id="img2" src="@Model.ImgEditModel.ImgEditViewModel.ImgPath2" class="defaultImg" alt="your image" />
                <br>
                <input type='file' name="productImg2" onchange="readURL2(this)" id="productImg2" />
                <br>
                <a onclick="readURL2(this);" asp-area="Administration" asp-controller="Img" asp-action="DeleteProductImg" asp-route-id="@Model.ImgEditModel.ImgEditViewModel.ProductId" asp-route-imgNumber="2" id="btn2" class="btn btn-outline-secondary">Изтрий снимката</a>
                <br>
            </div>
            <div id="pic3" style="float:left">
                <br>
                <img id="img3" src="@Model.ImgEditModel.ImgEditViewModel.ImgPath3" class="defaultImg" alt="your image" />
                <br>
                <input type='file' name="productImg3" onchange="readURL3(this)" id="productImg3" />
                <br>
                <a onclick="readURL3(this);" asp-area="Administration" asp-controller="Img" asp-action="DeleteProductImg" asp-route-id="@Model.ImgEditModel.ImgEditViewModel.ProductId" asp-route-imgNumber="3" id="btn3" class="btn btn-outline-secondary">Изтрий снимката</a>
                <br>
            </div>
            <div id="pic4" style="float:left">
                <br>
                <img id="img4" src="@Model.ImgEditModel.ImgEditViewModel.ImgPath4" class="defaultImg" alt="your image" />
                <br>
                <input type='file' name="productImg4" onchange="readURL4(this)" id="productImg4" />
                <br>
                <a onclick="readURL4(this);" asp-area="Administration" asp-controller="Img" asp-action="DeleteProductImg" asp-route-id="@Model.ImgEditModel.ImgEditViewModel.ProductId" asp-route-imgNumber="4" id="btn4" class="btn btn-outline-secondary">Изтрий снимката</a>
                <br>
            </div>
        </div>
        <div style="float:right;">
            <button onclick="upload()" id="btnSubmit" style="display:none;" type="submit" value="Upload Imgs" class="btn btn-primary">Качи снимката</button> <br />
        </div>
    </form>
</div>