Web/YovevElectric.Web/Controllers/MyAccountController.cs
namespace YovevElectric.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using YovevElectric.Common;
    using YovevElectric.Data.Models;
    using YovevElectric.Web.ViewModels.MyAccount;

    public class MyAccountController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public MyAccountController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult MyAccount()
        {
            return this.View();
        }

        public IActionResult ChangePassword()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.userManager.ChangePasswordAsync(user, input.OldPassword, input.NewPassword);
            return this.Redirect("/");
        }

        public IActionResult DeleteAccount()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAccount(DeleteAccountInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            if (user.Email == input.Email)
            {
                await this.signInManager.SignOutAsync();
                await this.userManager.DeleteAsync(user);
                return this.Redirect("/");
            }
            else
            {
                return this.View(input);
            }
        }
    }
}

Web/YovevElectric.Web/Views/Shared/_AccountNavPartial.cshtml
@using YovevElectric.Common;
@using YovevElectric.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "_AccountNavPartial";
}

<aside class="col-right sidebar col-sm-3 col-xs-12 wow bounceInUp animated animated" style="visibility: visible;">
    <div class="block block-account">
        <div class="block-title"> Моят акаунт </div>
        <div class="block-content">
            <ul>
                <li><a asp-area="" asp-controller="MyAccount" asp-action="ChangePassword"><span>Промени парола</span></a></li>
                <li><a asp-area="" asp-controller="MyAccount" asp-action="DeleteAccount"><span> Изтрии акаунт</span></a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Privacy"><span> Privacy</span></a></li>
                @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                {
                    <li><span> <h3>ADMIN MENU</h3></span></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="CreateProduct"><span>Добави продукт</span></a></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="CreateCategory"><span>Добави категория</span></a></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="CreateSubCategory"><span>Добави подкатегория</span></a></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="AllCategoriesAndSubCategories"><span>Всички категории и подкатегория</span></a></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="Orders"><span>Поръчки</span></a></li>
                    <li><a asp-area="Administration" asp-controller="Administration" asp-action="Discounts"><span>Отстъпки</span></a></li>
                }
            </ul>
        </div>
    </div>

</aside>

Web/YovevElectric.Web/Views/Shared/_AddProductToBagPartial.cshtml
@model YovevElectric.Web.ViewModels.Home.AllProductsViewModel;
@{
    ViewData["Title"] = "_AddProductToBagPartial";
}

<div class="modal" tabindex="-1" role="dialog" id="addProductToBagModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-area="" asp-controller="Bag" asp-action="AddToBag">
                    <div style="text-align:center">
                        <div>
                        <span>Избери количество</span>
                        <input type="hidden" asp-for="@Model.AddToBagInputModel.ProductId" id="productId">
                        <input type="number" asp-for="@Model.AddToBagInputModel.Quantity">
                        <span asp-validation-for="@Model.AddToBagInputModel.Quantity" class="text-danger" />
                        </div>
                        <button class="btn-primary" type="submit" style="float:right">Добави</button>
                        <br/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>